# use the latest ubuntu environment (18.04) available on travis
dist: xenial
language: go
env:
  - GO111MODULE=on
  - GOFLAGS='-race'
go:
  - 1.12.x
git:
depth: 1
install: true
notifications:
  email:
    recipients: fukpig2@gmail.com
    on_success: change
    on_failure: always
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin 1.16.0
script:
  - golangci-lint run
  - go test -v -race ./...
